<?php
define('GENPDF','PDF generálás');
define('QR','QR kód');
define('ADDCART','Hozzáadás a kosárhoz');
define('DESC','Leírás');
define('CART','Kosár');
define('ADDPRODUCT','Termék hozzáadása');
define('ADD','Hozzáadás');
define('PRICE', 'Ár');
define('NOPET','Nincs regisztrálva házi kedvenc a fiókján.');
define('INFO', 'Elérhetőségét a QR-kód tárolja. Rögzítheti kedvence nyakörvére.');
define('VETS', 'Állatorvosok');
define('PRODUCT', 'Termékek');
define('ADDPET','Házikedvenc regisztrálása');
define('MYPETS','Házi kedvenceim');
define('DOG','Kutya');
define('CAT','Macska');
define('BUNNY','Nyúl');
define('PARROT','Papagáj');
define('PIG','Malac');
define('SPECIES','Faj');
define('BREED','Fajta');
define('REGTIME','Regisztrálás dátuma');
define('PRIVILEGE','Jog');
define('SAVE','Mentés');
define('SETTINGS','Beállítások');
define('NUMBER','Szám');
define('LOGOUT', 'Kijelentkezés');
define('PHONE','Telefonszám');
define('REGHERE','Itt regisztrálhat!');
define('NOACC','Nem rendelkezik fiókkal?');
define('PASSWORD','Jelszó');
define('CONFPASS','Jelszó megerősítése');
define('REGISTER','Regisztrálás');
define('LOGIN','Bejelentkezés');
define('ACCOUNT','Fiók');
define('BACK','Vissza');
define('LG','Nyelv');
define('LANGUAGE_sr', 'Szerb');
define('LANGUAGE_hu', 'Magyar');
define('LANGUAGE_en', 'Angol');
define('HOME','Kezdőoldal');
define('WELCOME_MESSAGE', 'Üdvözöljük a weboldalon!');
define('ABOUT_US_TITLE', 'Rólunk');
define('JOBS_TITLE', 'Álláshirdetés');
define('NAME', 'Név');
define('LASTNAME', 'Vezetéknév');
define('BIRTH_DATE', 'Születési dátum');
define('RESUME', 'Önéletrajz');
define('SKILLS', 'Programozási készségek');
define('EMAIL', 'E-mail cím');
define('SUBMIT', 'Küldés');
define('RESET', 'Visszaállítás');
define('SUCCESS_MESSAGE', 'Sikeresen jelentkezett az álláshirdetésre.');
define('BACK_TO_JOBS', 'Visszatérés az álláshirdetéshez');
define('ERROR_MESSAGE', 'Kérjük, töltse ki az összes mezőt helyesen.');
?>
