<?php
define('ADDVET','Dodaj novog veterinara');
define('CHANGEPS','Izmeni lozinku');
define('RESERVE','Rezerviraj');
define('GENPDF','Generiši PDF');
define('QR','QR kod');
define('ADDCART','Dodaj u korpu');
define('DESC','Opis');
define('CART','Korpa');
define('ADDPRODUCT','Dodaj novi proizvod');
define('ADD','Dodaj');
define('PRICE', 'Cena');
define('NOPET','Nemate nijednog kućnog ljubimca registrovanog na vašem nalogu.');
define('INFO', 'Vaše kontakt informacije se čuvaju u KR kodu. Možete ga pričvrstiti na ogrlicu vašeg ljubimca.');
define('VETS', 'Veterinari');
define('PRODUCT', 'Proizvodi');
define('ADDPET','Registrovanje ljubimca');
define('MYPETS','Moji ljubimci');
define('DOG','Pas');
define('CAT','Mačka');
define('BUNNY','Zec');
define('PARROT','Papagaj');
define('PIG','Prase');
define('SPECIES','Vrsta');
define('BREED','Rasa');
define('REGTIME','Datum registracije');
define('PRIVILEGE','Privilegija');
define('SAVE','Sačuvaj');
define('SETTINGS','Podešavanja');
define('NUMBER','Broj');
define('LOGOUT', 'Izjavljivanje');
define('PHONE','Broj telefona');
define('REGHERE','Ovde možete registrovati!');
define('NOACC','Nemate nalog?');
define('CONFPASS','Ponavjanje lozinke');
define('PASSWORD','Lozinka');
define('REGISTER','Registracija');
define('LOGIN','Prijava');
define('ACCOUNT','Nalog');
define('BACK','Nazad');
define('LG','Jezik');
define('LANGUAGE_sr', 'Srpski');
define('LANGUAGE_hu', 'Mađarski');
define('LANGUAGE_en', 'Engleski');
define('HOME','Naslovna strana');
define('WELCOME_MESSAGE', 'Dobrodošli na veb stranicu!');
define('ABOUT_US_TITLE', 'O nama');
define('JOBS_TITLE', 'Oglas za posao');
define('NAME', 'Ime');
define('LASTNAME', 'Prezime');
define('BIRTH_DATE', 'Datum rodjenja');
define('RESUME', 'CV');
define('SKILLS', 'Veštine programiranja');
define('EMAIL', 'E-mail adresa');
define('SUBMIT', 'Slanje');
define('RESET', 'Otkaži');
define('SUCCESS_MESSAGE', 'Uspešno ste se prijavili na oglas za posao.');
define('BACK_TO_JOBS', 'Vratite se na oglas za posao');
define('ERROR_MESSAGE', 'Molimo Vas da ispravno popunite sva polja.');
define('PRODUCTDESCRIPTION','Informacija o proizvodu');
define('USERS','Korisnici');
define('UPDATE','Ažurirati');
define('UPDATE_PET','Modifikacija ljubimaca');
define('DELETE_PET','Izbriši ljubimca');
define('REVIEV_MESSAGE',"<h2>Molimo ocenite našeg veterinara</h2> Molimo vas da ocenite našeg veterinara
 odlaskom na ovaj link, što važi 72 sata. To puno pomaže da saznamo kako naši radnici komuniciraju sa vlasnicima:<br>");
define('BACK_TO_RATINGS','Nazad na ocenima');
?>

