<?php
define('DOWNLOAD_QRCODE','Preuzimanje QRCode slike');
define("TIME",'Vreme:');
define('DATE','Datum:');
define('PET_RESERVATION'," je zakazao termin za pregled ljubimca: ");
define('RESERVED_APOINTMENT_TITLE_VET','Zakazani termini kod korisnika:');
define('PETS_VETERINARIAN','Veterinar ljubimca: ');
define('RESCRSUC','Rezervacija je uspešno napravljena.');
define('DATAMIS','Podaci nedostaju');
define('ERROR','Greške u sistemu');
define('PASSUPDF', 'Promena lozinka nije nije bila uspešna');
define('PASSUPD', 'Lozinka je uspešno izmenjena');
define('PASSNONUM', 'Lozinka mora da sadrži brojeve');
define('PASSNOUP', 'Lozinka mora da sadrži velika slova');
define('PASSNOLOW', 'Lozinka mora da sadrži mala slova');
define('PASSMATCH','Lozinke se ne poklapaju');
define('PASSFILL','Polja za lozinku nisu popunjena');
define('NOEX','Ova email addressa ne postoji');
define('FB','Hvala za povratne informacije');
define('BACK_TO_VET_SELECTION','Nazad na stranicu za veterinara');
define('SELECT_TIME','Izaberite Vreme');
define('SELECT_PET','Izaberite ljubimca:');
define('RESERVED_VETERINARIAN','Zakazan termin kod veterinara:');
define('RESERVED_APOINTMENT_TITLE','Zakazani termini kod veterinara:');
define('RESERVED_PETS_TITLE','Zakazani termini');
define('DELETE_RESERVATION_BUTTON','Odkaži termin');
define('UNBAN_BUTTON','Otključavanje');
define('BAN_BUTTON','Zabrani');
define('DELETE_PICTURE', 'Izbirišite profil sliku');
define("RESESEVATION_CANCELED_BY_VET",'Pregled Odkazano');
define('HERE','ovde');
define('BAN','Osoba je zabranjena:');
define('UNBAN','Osoba nije zabranjena:');
define('FILLMES','Popunite poruku');
define('RESDELFAIL','Brisanje rezervacije nije uspelo. Pokušajte ponovo.');
define('RESDELSUC','Rezervacija je uspešno obrisana.');
define('PICSUCCESS','Slika je uspešno izbrisana');
define('VERFAIL','Verifikacija nije uspela');
define('LOGSET','Prijavite se i završite podešavanje naloga');
define('EMAILNOTREG','Ovaj email nije registrovan.');
define('CODENOVALID','Ovaj kod nije važeći na našoj stranici');
define('CHANGEPASS','Sada možete promeniti lozinku.');
define('VALIDEXP','Vreme valjanosti je isteklo. Zatražite novi kod.');
define('NOCHECK','Ne možete proveriti kućnog ljubimca dan ili više pre zakazanog termina');
define('SEEVET','Lista veterinara');
define('RESERVATION','Rezervacija od: ');
define('RESERVATION2','Do: ');
define('RESERVATION3','Datum rezervacije: ');
define('WELCOME','Dobrodošli u R&D, našu veterinarsku platformu!');
define('WELCOME2','Vaše jedinstveno rešenje za upravljanje zdravlje i blagostanje vaših ljubimaca!');
define('REG1','Registrujte svoje ljubimce');
define('REG2','Kreirajte personalizovani profil za svakog ljubimca, uključujući osnovne informacije kao što su rasa, starost, medicinska istorija i status vakcinacije.');
define('BOOK1','Rezervišite termin');
define('BOOK2','Izaberite svog omiljenog veterinara i rezervišite termin koji vam odgovara, sve iz udobnosti vašeg doma.');
define('QR1','Ispišite QR kodove');
define('QR2','Generišite QR kodove sa informacijama o vašem ljubimcu i vašim kontakt podacima. Idealno za ogrlice u slučaju da vaš ljubimac zaluta.');
define('RATE1','Ocijenite veterinare');
define('RATE2','Pomozite drugim vlasnicima ljubimaca ocenjivanjem i pisanjem recenzija veterinara na osnovu vašeg iskustva.');
define('SHOP1','Kupite preporučene proizvode');
define('SHOP2','Pregledajte našu odabranu kolekciju proizvoda za ljubimce, od visokokvalitetne hrane do zabavnih igračaka, sve preporučeno od strane stručnjaka.');
define('SUM_PROD','Količina');
define('TOTAL_PRICE','Ukupna cena');
define('DETAILS','Detalji');
define('MODIFY','Podešajl');
define('ADDVET','Dodaj novog veterinara');
define('CHANGEPS','Izmeni lozinku');
define('RESERVE','Rezerviraj');
define('GENPDF','Generiši PDF');
define('QR','QR kod');
define('ADDCART','Dodaj u korpu');
define('DESC','Opis');
define('CART','Korpa');
define('ADDPRODUCT','Dodaj novi proizvod');
define('ADD','Dodaj');
define('PRICE', 'Cena');
define('NOPET','Nemate nijednog kućnog ljubimca registrovanog na vašem nalogu.');
define('INFO', 'Vaše kontakt informacije se čuvaju u KR kodu. Možete ga pričvrstiti na ogrlicu vašeg ljubimca.');
define('VETS', 'Veterinari');
define('PRODUCT', 'Proizvodi');
define('ADDPET','Registrovanje ljubimca');
define('MYPETS','Moji ljubimci');
define('DOG','Pas');
define('CAT','Mačka');
define('BUNNY','Zec');
define('PARROT','Papagaj');
define('PIG','Prase');
define('SPECIES','Vrsta');
define('BREED','Rasa');
define('REGTIME','Datum registracije');
define('PRIVILEGE','Privilegija');
define('SAVE','Sačuvaj');
define('SETTINGS','Podešavanja');
define('NUMBER','Broj');
define('LOGOUT', 'Izjavljivanje');
define('PHONE','Broj telefona');
define('REGHERE','Ovde možete registrovati!');
define('NOACC','Nemate nalog?');
define('CONFPASS','Ponavjanje lozinke');
define('PASSWORD','Lozinka');
define('REGISTER','Registracija');
define('LOGIN','Prijava');
define('ACCOUNT','Nalog');
define('BACK','Nazad');
define('LG','Jezik');
define('LANGUAGE_sr', 'Srpski');
define('LANGUAGE_hu', 'Mađarski');
define('LANGUAGE_en', 'Engleski');
define('HOME','Naslovna strana');
define('WELCOME_MESSAGE', 'Dobrodošli na veb stranicu!');
define('ABOUT_US_TITLE', 'O nama');
define('JOBS_TITLE', 'Oglas za posao');
define('NAME', 'Ime');
define('LASTNAME', 'Prezime');
define('BIRTH_DATE', 'Datum rodjenja');
define('RESUME', 'CV');
define('SKILLS', 'Veštine programiranja');
define('EMAIL', 'E-mail adresa');
define('SUBMIT', 'Slanje');
define('RESET', 'Otkaži');
define('SUCCESS_MESSAGE', 'Uspešno ste se prijavili na oglas za posao.');
define('BACK_TO_JOBS', 'Vratite se na oglas za posao');
define('ERROR_MESSAGE', 'Molimo Vas da ispravno popunite sva polja.');
define('PRODUCTDESCRIPTION','Informacija o proizvodu');
define('USERS','Korisnici');
define('UPDATE','Ažurirati');
define('UPDATE_PET','Modifikacija ljubimaca');
define('DELETE_PET','Izbriši ljubimca');
define('REVIEV_MESSAGE',"<h2>Molimo ocenite našeg veterinara</h2> Molimo vas da ocenite našeg veterinara
 odlaskom na ovaj link, što važi 72 sata. To puno pomaže da saznamo kako naši radnici komuniciraju sa vlasnicima:<br>");
define('BACK_TO_RATINGS','Nazad na ocenima');
?>

