<?php
define('WELCOME','Welcome to R&D, our Veterinary Platform!');
define('WELCOME2','Your one-stop solution for managing your petses health and well-being!');
define('REG1','Register you pets');
define('REG2','Create a personalized profile for each pet, including essential details like their breed, age, medical history, and vaccination status.');
define('BOOK1','Book appointments');
define('BOOK2','Choose your preferred veterinarian and book an appointment that suits your schedule, all from the comfort of your home.');
define('QR1','Print QR Codes');
define('QR2','Generate QR codes with your petses information and your contact details. Perfect for collars in case your pet gets lost.');
define('RATE1','Rate Veterinarians');
define('RATE2','Help other pet owners by rating and reviewing veterinarians based on your experience.');
define('SHOP1','Shop Recommended Products');
define('SHOP2','Browse our curated collection of pet supplies, from high-quality food to fun toys, all recommended by experts.');
define('SUM_PROD','Quantity');
define('TOTAL_PRICE','Total Price');
define('DETAILS','Details');
define('MODIFY','Modify');
define('ADDVET','Add veterinarian');
define('CHANGEPS','Change password');
define('RESERVE','Reserve');
define('GENPDF','Generate PDF');
define('QR','QR code');
define('ADDCART','Add to cart');
define('DESC','Description');
define('CART','Cart');
define('ADDPRODUCT','Add product');
define('ADD','Add');
define('PRICE','Price');
define('NOPET','You do not have any pets registered to your account.');
define('INFO','Your contact information is stored <br>in the QR Code. You may attach it to your pet\'s collar.');
define('VETS', 'Veterinarians');
define('PRODUCT', 'Products');
define('ADDPET','Register a pet');
define('MYPETS','My pets');
define('DOG','Dog');
define('CAT','Cat');
define('BUNNY','Bunny');
define('PARROT','Parrot');
define('PIG','Pig');
define('SPECIES','Species');
define('BREED','Breed');
define('REGTIME','Registration date');
define('PRIVILEGE', 'Privilage');
define('SAVE','Save');
define('SETTINGS','Settings');
define('NUMBER','Number');
define('LOGOUT', 'Log out');
define('PHONE','Phone number');
define('REGHERE','Register here!');
define('NOACC','Dont have an account?');
define('CONFPASS','Confirm password');
define('PASSWORD','Password');
define('REGISTER','Register');
define('LOGIN','Log in');
define('ACCOUNT','Account');
define('BACK','Back');
define('LG','Language');
define('LANGUAGE_sr', 'Serbian');
define('LANGUAGE_hu', 'Hungarian');
define('LANGUAGE_en', 'English');
define('HOME','Home');
define('WELCOME_MESSAGE','Welcome to the website!');
define('ABOUT_US_TITLE', 'About us');
define('JOBS_TITLE', 'Looking for jobs');
define('NAME', 'Name');
define('LASTNAME', 'Lastname');
define('BIRTH_DATE', 'Date of Birth');
define('RESUME', 'Resume');
define('SKILLS', 'Skills');
define('EMAIL', 'E-mail address');
define('SUBMIT', 'Send');
define('RESET', 'Reset');
define('SUCCESS_MESSAGE', 'You have successfully registered!.');
define('BACK_TO_JOBS', 'Back to jobs');
define('ERROR_MESSAGE', 'Error, please fill all the fields.');
define('PRODUCTDESCRIPTION','Product description');
define('USERS','Users');
define('UPDATE','Update');
define('UPDATE_PET','Update Pet');
define('DELETE_PET','Delete Pet');
define('REVIEV_MESSAGE',"<h2>Please rate our Veterinarian</h2> Please rate our veterinarian by going to this link, that is active for 72 hours.
It help a lot to now our workers are communicationg with the owners:<br>");
define('BACK_TO_RATINGS','Back to ratings');
?>
