<?php
define('ADDVET','Add veterinarian');
define('CHANGEPS','Change password');
define('RESERVE','Reserve');
define('GENPDF','Generate PDF');
define('QR','QR code');
define('ADDCART','Add to cart');
define('DESC','Description');
define('CART','Cart');
define('ADDPRODUCT','Add product');
define('ADD','Add');
define('PRICE','Price');
define('NOPET','You do not have any pets registered to your account.');
define('INFO','Your contact information is stored <br>in the QR Code. You may attach it to your pet\'s collar.');
define('VETS', 'Veterinarians');
define('PRODUCT', 'Products');
define('ADDPET','Register a pet');
define('MYPETS','My pets');
define('DOG','Dog');
define('CAT','Cat');
define('BUNNY','Bunny');
define('PARROT','Parrot');
define('PIG','Pig');
define('SPECIES','Species');
define('BREED','Breed');
define('REGTIME','Registration date');
define('PRIVILEGE', 'Privilage');
define('SAVE','Save');
define('SETTINGS','Settings');
define('NUMBER','Number');
define('LOGOUT', 'Log out');
define('PHONE','Phone number');
define('REGHERE','Register here!');
define('NOACC','Dont have an account?');
define('CONFPASS','Confirm password');
define('PASSWORD','Password');
define('REGISTER','Register');
define('LOGIN','Log in');
define('ACCOUNT','Account');
define('BACK','Back');
define('LG','Language');
define('LANGUAGE_sr', 'Serbian');
define('LANGUAGE_hu', 'Hungarian');
define('LANGUAGE_en', 'English');
define('HOME','Home');
define('WELCOME_MESSAGE','Welcome to the website!');
define('ABOUT_US_TITLE', 'About us');
define('JOBS_TITLE', 'Looking for jobs');
define('NAME', 'Name');
define('LASTNAME', 'Lastname');
define('BIRTH_DATE', 'Date of Birth');
define('RESUME', 'Resume');
define('SKILLS', 'Skills');
define('EMAIL', 'E-mail address');
define('SUBMIT', 'Send');
define('RESET', 'Reset');
define('SUCCESS_MESSAGE', 'You have successfully registered!.');
define('BACK_TO_JOBS', 'Back to jobs');
define('ERROR_MESSAGE', 'Error, please fill all the fields.');
define('PRODUCTDESCRIPTION','Product description');
define('USERS','Users');
define('UPDATE','Update');
define('UPDATE_PET','Update Pet');
define('DELETE_PET','Delete Pet');
define('REVIEV_MESSAGE',"<h2>Please rate our Veterinarian</h2> Please rate our veterinarian by going to this link, that is active for 72 hours.
It help a lot to now our workers are communicationg with the owners:<br>")

?>
