<?php
define('BAN','Személy letiltva:');
define('UNBAN','Személy tilalma felmentve:');
define('FILLMES','Töltse ki az üzenetet');
define('RESDELFAIL','Nem sikerült törölni a foglalást. Kérjük, próbálja újra.');
define('RESDELSUC','Foglalás sikeresen törölve');
define('PICSUCCESS','A kép sikeresen törölve');
define('VERFAIL','Az ellenőrzés nem sikerült');
define('LOGSET','Jelentkezzen be, és fejezze be fiókja beállítását');
define('EMAILNOTREG','Ez az e-mail nincs regisztrálva.');
define('CODENOVALID','Ez a kód nem érvényes oldalunkon');
define('CHANGEPASS','Most megváltoztathatja jelszavát.');
define('VALIDEXP','Az érvényesítési idő lejárt. Kérjen új kódot.');
define('NOCHECK','A találkozó előtt egy nappal vagy többel nem ellenőrizhető az állat');
define('SEEVET','Állatorvosok megtekintése');
define('RESERVATION','Foglalás ettől: ');
define('RESERVATION2','Eddig: ');
define('RESERVATION3','Foglalás dátuma: ');
define('WELCOME','Üdvözöljük az R&D-nél, a mi állatorvosi platformunkon!');
define('WELCOME2','Az Ön egyablakos megoldása a háziállatai egészségének és jólétének fenntartására!');
define('REG1','Regisztrálja a háziállatait');
define('REG2','Hozzon létre egy személyre szabott profilt minden egyes háziállata számára, beleértve olyan alapvető adatokat, mint a fajtájuk, életkoruk, orvosi előzményeik és oltási státuszuk.');
define('BOOK1','Foglaljon időpontot');
define('BOOK2','Válassza ki a preferált állatorvosát, és foglaljon időpontot, amely megfelel az Ön időpontjainak, mindezt otthona kényelméből.');
define('QR1','Nyomtassa ki a QR-kódokat');
define('QR2','Generáljon QR-kódokat a háziállatai információival és az Ön elérhetőségi adataival. Tökéletes a nyakörvekhez, ha a háziállata elveszne.');
define('RATE1','Értékelje az állatorvosokat');
define('RATE2','Segítsen más háziállat-tulajdonosoknak az állatorvosok értékelésével és véleményezésével, a saját tapasztalatai alapján.');
define('SHOP1','Vásároljon ajánlott termékeket');
define('SHOP2','Böngéssze végig válogatott háziállat-ellátmányainkat, a kiváló minőségű ételektől a szórakoztató játékokig, mindet szakértők ajánlják.');
define('SUM_PROD','Mennyiség');
define('TOTAL_PRICE','Összegzett ár');
define('DETAILS','Részletek');
define('MODIFY', 'Szerkesztés');
define('ADDVET','Állatorvos hozzáadása');
define('CHANGEPS','Jelszóváltoztatás');
define('RESERVE','Lefoglalás');
define('GENPDF','PDF generálás');
define('QR','QR kód');
define('ADDCART','Hozzáadás a kosárhoz');
define('DESC','Leírás');
define('CART','Kosár');
define('ADDPRODUCT','Termék hozzáadása');
define('ADD','Hozzáadás');
define('PRICE', 'Ár');
define('NOPET','Nincs regisztrálva házi kedvenc a fiókján.');
define('INFO', 'Elérhetőségét a QR-kód tárolja. Rögzítheti kedvence nyakörvére.');
define('VETS', 'Állatorvosok');
define('PRODUCT', 'Termékek');
define('ADDPET','Házikedvenc regisztrálása');
define('MYPETS','Házi kedvenceim');
define('DOG','Kutya');
define('CAT','Macska');
define('BUNNY','Nyúl');
define('PARROT','Papagáj');
define('PIG','Malac');
define('SPECIES','Faj');
define('BREED','Fajta');
define('REGTIME','Regisztrálás dátuma');
define('PRIVILEGE','Jog');
define('SAVE','Mentés');
define('SETTINGS','Beállítások');
define('NUMBER','Szám');
define('LOGOUT', 'Kijelentkezés');
define('PHONE','Telefonszám');
define('REGHERE','Itt regisztrálhat!');
define('NOACC','Nem rendelkezik fiókkal?');
define('PASSWORD','Jelszó');
define('CONFPASS','Jelszó megerősítése');
define('REGISTER','Regisztrálás');
define('LOGIN','Bejelentkezés');
define('ACCOUNT','Fiók');
define('BACK','Vissza');
define('LG','Nyelv');
define('LANGUAGE_sr', 'Szerb');
define('LANGUAGE_hu', 'Magyar');
define('LANGUAGE_en', 'Angol');
define('HOME','Kezdőoldal');
define('WELCOME_MESSAGE', 'Üdvözöljük a weboldalon!');
define('ABOUT_US_TITLE', 'Rólunk');
define('JOBS_TITLE', 'Álláshirdetés');
define('NAME', 'Név');
define('LASTNAME', 'Vezetéknév');
define('BIRTH_DATE', 'Születési dátum');
define('RESUME', 'Önéletrajz');
define('SKILLS', 'Programozási készségek');
define('EMAIL', 'E-mail cím');
define('SUBMIT', 'Küldés');
define('RESET', 'Visszaállítás');
define('SUCCESS_MESSAGE', 'Sikeresen jelentkezett az álláshirdetésre.');
define('BACK_TO_JOBS', 'Visszatérés az álláshirdetéshez');
define('ERROR_MESSAGE', 'Kérjük, töltse ki az összes mezőt helyesen.');
define('PRODUCTDESCRIPTION','Termék leírás');
define('USERS','Felhaszálók');
define('UPDATE','Frissítés');
define('UPDATE_PET','Házikedvenc módosítása');
define('DELETE_PET','Házikedvenc törlése');
define('REVIEV_MESSAGE',"<h2>Kérjük értékelje állatorvosunkat</h2> Kérjük értékelje állatorvosunkat az alábbi linken, ami 72 óráig érvényes.
 Nagy segítség számunkra, hogy megtudjuk, hogyan kommunikálnak dolgozóink a gazdákkal:<br>");
define('BACK_TO_RATINGS','Vissza az értékelésre');
?>
