<?php
define('DESCRIPTION_VET_UPDATED','Your description has been updated.');
define('DESCRIPTION_VET','Your description');
define('ADD_DESCRIPTION_VET','Add or modify your description');
define('DOWNLOAD_QRCODE','Download QRCode');
define("TIME",'Time:');
define('DATE','Date:');
define('PET_RESERVATION'," made a reservation for yor pet named: ");
define('RESERVED_APOINTMENT_TITLE_VET','Reserve Appointment for User:');
define('PETS_VETERINARIAN','The pets veterinarian is: ');
define('DATAMIS','Data missing');
define('ERROR','An error occurred');
define('PASSUPDF','Failed to update password!');
define('PASSUPD','Password updated successfully!');
define('PASSNOEIGHT', 'Password must be at least 8 characters long');
define('PASSNONUM', 'Password must contain numbers');
define('PASSNOUP', 'Password must contain upper case letters');
define('PASSNOLOW', 'Password must contain lower case letters');
define('PASSMATCH','The passwords do not match');
define('PASSFILL','The password fields are not filled out');
define('NOEX','This email address doesnt exist');
define('FB','Thank you for your feedback');
define('BACK_TO_VET_SELECTION','Back to Veterinarian Selection');
define('SELECT_TIME','Select Time');
define('SELECT_PET','Select Pet:');
define('RESERVED_VETERINARIAN','Reserve for veterinarian:');
define('RESERVED_APOINTMENT_TITLE','Reserve Appointment for Veterinarian:');
define('RESERVED_PETS_TITLE','Reserved Pets');
define('DELETE_RESERVATION_BUTTON','Delete reservation');
define('UNBAN_BUTTON','Unban');
define('BAN_BUTTON','Ban');
define('DELETE_PICTURE', 'Delete Picture');
define("RESESEVATION_CANCELED_BY_VET",'Reservation Cancelled');
define('HERE','here');
define('BAN','This person is banned:');
define('UNBAN','This person is unbanned:');
define('FILLMES','Fill the message out.');
define('RESDELFAIL','Failed to delete the reservation. Please try again.');
define('RESCRSUC','Reservation successfully created.');
define('RESDELSUC','Reservation successfully deleted.');
define('PICSUCCESS','Picture deleted successfully');
define('VERFAIL','Verification failed');
define('LOGSET','Log in and finish setting up your account');
define('EMAILNOTREG','This email is not registered.');
define('CODENOVALID','This code is not valid on our page');
define('CHANGEPASS','Now you can change the password.');
define('VALIDEXP','Validation time has expired. Please request a new code.');
define('NOCHECK','Cannot check pet a day or more before the appointment');
define('SEEVET','List of veterinarians');
define('RESERVATION','Reservation From: ');
define('RESERVATION2','To: ');
define('RESERVATION3','Reservation Date: ');
define('WELCOME','Welcome to R&D, our Veterinary Platform!');
define('WELCOME2','Your one-stop solution for managing your petses health and well-being!');
define('REG1','Register your pets');
define('REG2','Create a personalized profile for each pet, including essential details like their breed, age, medical history, and vaccination status.');
define('BOOK1','Book appointments');
define('BOOK2','Choose your preferred veterinarian and book an appointment that suits your schedule, all from the comfort of your home.');
define('QR1','Print QR Codes');
define('QR2','Generate QR codes with your petses information and your contact details. Perfect for collars in case your pet gets lost.');
define('RATE1','Rate Veterinarians');
define('RATE2','Help other pet owners by rating and reviewing veterinarians based on your experience.');
define('SHOP1','Shop Recommended Products');
define('SHOP2','Browse our curated collection of pet supplies, from high-quality food to fun toys, all recommended by experts.');
define('SUM_PROD','Quantity');
define('TOTAL_PRICE','Total Price');
define('DETAILS','Details');
define('MODIFY','Modify');
define('ADDVET','Add veterinarian');
define('CHANGEPS','Change password');
define('RESERVE','Reserve');
define('GENPDF','Generate PDF');
define('QR','QR code');
define('ADDCART','Add to cart');
define('DESC','Description');
define('CART','Cart');
define('ADDPRODUCT','Add product');
define('ADD','Add');
define('PRICE','Price');
define('NOPET','You do not have any pets registered to your account.');
define('INFO','Your contact information is stored <br>in the QR Code. You may attach it to your pet\'s collar.');
define('VETS', 'Veterinarians');
define('PRODUCT', 'Products');
define('ADDPET','Register a pet');
define('MYPETS','My pets');
define('DOG','Dog');
define('CAT','Cat');
define('BUNNY','Bunny');
define('PARROT','Parrot');
define('PIG','Pig');
define('SPECIES','Species');
define('BREED','Breed');
define('REGTIME','Registration date');
define('PRIVILEGE', 'Privilage');
define('SAVE','Save');
define('SETTINGS','Settings');
define('NUMBER','Number');
define('LOGOUT', 'Log out');
define('PHONE','Phone number');
define('REGHERE','Register here!');
define('NOACC','Dont have an account?');
define('CONFPASS','Confirm password');
define('PASSWORD','Password');
define('REGISTER','Register');
define('LOGIN','Log in');
define('ACCOUNT','Account');
define('BACK','Back');
define('LG','Language');
define('LANGUAGE_sr', 'Serbian');
define('LANGUAGE_hu', 'Hungarian');
define('LANGUAGE_en', 'English');
define('HOME','Home');
define('WELCOME_MESSAGE','Welcome to the website!');
define('ABOUT_US_TITLE', 'About us');
define('JOBS_TITLE', 'Looking for jobs');
define('NAME', 'Name');
define('LASTNAME', 'Lastname');
define('BIRTH_DATE', 'Date of Birth');
define('RESUME', 'Resume');
define('SKILLS', 'Skills');
define('EMAIL', 'E-mail address');
define('SUBMIT', 'Send');
define('RESET', 'Reset');
define('SUCCESS_MESSAGE', 'You have successfully registered!.');
define('BACK_TO_JOBS', 'Back to jobs');
define('ERROR_MESSAGE', 'Error, please fill all the fields.');
define('PRODUCTDESCRIPTION','Product description');
define('USERS','Users');
define('UPDATE','Update');
define('UPDATE_PET','Update Pet');
define('DELETE_PET','Delete Pet');
define('REVIEV_MESSAGE',"<h2>Please rate our Veterinarian</h2> Please rate our veterinarian by going to this link, that is active for 72 hours.
It help a lot to now our workers are communicationg with the owners:<br>");
define('BACK_TO_RATINGS','Back to ratings');
?>
