<?php
define('NOPET','Nemate nijednog kućnog ljubimca registrovanog na vašem nalogu.');
define('INFO', 'Vaše kontakt informacije se čuvaju u KR kodu. Možete ga pričvrstiti na ogrlicu vašeg ljubimca.');
define('VETS', 'Veterinari');
define('PRODUCT', 'Proizvodi');
define('ADDPET','registrovanje ljubimca');
define('MYPETS','Moji ljubimci');
define('DOG','Pas');
define('CAT','Mačka');
define('BUNNY','Zec');
define('PARROT','Papagaj');
define('PIG','Prase');
define('SPECIES','Vrsta');
define('BREED','Rasa');
define('REGTIME','Datum registracije');
define('PRIVILEGE','Privilegija');
define('SAVE','Sačuvaj');
define('SETTINGS','Podešavanja');
define('NUMBER','Broj');
define('LOGOUT', 'Izjavljivanje');
define('PHONE','Broj telefona');
define('REGHERE','Ovde možete registrovati!');
define('NOACC','Nemate nalog?');
define('CONFPASS','Ponavjanje lozinke');
define('PASSWORD','Lozinka');
define('REGISTER','Registracija');
define('LOGIN','Prijava');
define('ACCOUNT','Nalog');
define('BACK','Nazad');
define('LG','Jezik');
define('LANGUAGE_sr', 'Srpski');
define('LANGUAGE_hu', 'Mađarski');
define('LANGUAGE_en', 'Engleski');
define('HOME','Naslovna strana');
define('WELCOME_MESSAGE', 'Dobrodošli na veb stranicu!');
define('ABOUT_US_TITLE', 'O nama');
define('JOBS_TITLE', 'Oglas za posao');
define('NAME', 'Ime');
define('LASTNAME', 'Prezime');
define('BIRTH_DATE', 'Datum rodjenja');
define('RESUME', 'CV');
define('SKILLS', 'Veštine programiranja');
define('EMAIL', 'E-mail adresa');
define('SUBMIT', 'Slanje');
define('RESET', 'Otkaži');
define('SUCCESS_MESSAGE', 'Uspešno ste se prijavili na oglas za posao.');
define('BACK_TO_JOBS', 'Vratite se na oglas za posao');
define('ERROR_MESSAGE', 'Molimo Vas da ispravno popunite sva polja.');
?>

